language: php

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lynx

php:
  - 7.0

install:
  - composer install
  - npm install
  - gulp

script: phpunit --coverage-html ./tests/php/coverage/html

after_success:
  - clear
  - lynx -dump http://www.domanamon.com/Deploy.php

git:
  depth: 1

notifications:
  email:
    - john@domanamon.com

#after_failure:
#after_script:
#before_deploy:
#deploy:
#after_deploy:
#before_script:
