language: php

sudo: required
dist: trusty

services:
  - mysql

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - lynx

before_install:
  - mysql -u root -e 'create database domanamon_test;'

php:
  - 7.0

install:
  - npm install -g bower
  - composer install
  - npm install --only=dev
  - bower install
  - gulp
  - npm install --only=prod

script: phpunit

after_success:
  - ./.travis_deployment_script.sh

git:
  depth: 1

notifications:
  email:
    - john@domanamon.com

branches:
  only:
    - master
    - stable
    - staging
    
#after_failure:
#after_script:
#before_deploy:
#deploy:
#after_deploy:
#before_script:
